[package]
name = "tile-server"
version = "0.1.0"
authors = ["Laurențiu Nicola <lnicola@dend.ro>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.4"
actix-files = "0.4"
actix-web = "3.1"
failure = "0.1"
gdal = { git = "https://github.com/georust/gdal" }
gdal-sys = { git = "https://github.com/georust/gdal" }
